szam1 = input('Kérem az első számot 1-Bármeddig: ')
szam2 = input('Kérem a második számot 1-Bármeddig: ')
szam1 = int(szam1)
szam2 = int(szam2)
print('A két szám szorzata:',szam1 * szam2)
print('A két szám összege:',szam1 + szam2)
print('A két szám különbsége:',szam1 - szam2)